Repository Fashion-Cloud/backend, pull requests merged in 2023-08, with the labels that each got.

#109 chore: 깃헙 이슈 라벨별 템플릿 추가
  .github/ISSUE_TEMPLATE/chore_request.md
  .github/ISSUE_TEMPLATE/docs_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help_request.md
  .github/ISSUE_TEMPLATE/issue_request.md
  .github/ISSUE_TEMPLATE/refactoring_request.md
Labels: 환경설정

#107 [refactor/#105] 날씨 조회 로직 리팩토링
  src/main/java/com/techeer/fashioncloud/domain/geo/constant/GeoConstant.java
  src/main/java/com/techeer/fashioncloud/domain/geo/controller/AddressController.java
  src/main/java/com/techeer/fashioncloud/domain/geo/dto/AddressResponse.java
  src/main/java/com/techeer/fashioncloud/domain/geo/dto/GeoApiRequest.java
  src/main/java/com/techeer/fashioncloud/domain/geo/dto/GeoApiResponse.java
  src/main/java/com/techeer/fashioncloud/domain/geo/exception/KakaoApiException.java
  src/main/java/com/techeer/fashioncloud/domain/geo/service/AddressService.java
  src/main/java/com/techeer/fashioncloud/domain/geo/util/GeoApiCaller.java
  src/main/java/com/techeer/fashioncloud/domain/geo/util/GeoApiParser.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/constant/RainfallType.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/WeatherController.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/UltraSrtFcstResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/UltraSrtNcstResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/WeatherInfoResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/external/WeatherApiRequest.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/external/WeatherApiResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/exception/KakaoApiException.java
  src/main/java/com/techeer/fashioncloud/domain/weather/exception/WeatherApiException.java
  src/main/java/com/techeer/fashioncloud/domain/weather/forecast/ApiParsable.java
  src/main/java/com/techeer/fashioncloud/domain/weather/forecast/Forecast.java
  src/main/java/com/techeer/fashioncloud/domain/weather/forecast/UltraSrtFcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/forecast/UltraSrtNcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/forecast/VilageFcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/forecast/WeatherApiCallable.java
  src/main/java/com/techeer/fashioncloud/domain/weather/position/Coordinate.java
  src/main/java/com/techeer/fashioncloud/domain/weather/position/Location.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/AddressService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherCacheService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/util/WeatherApiCaller.java
  src/main/java/com/techeer/fashioncloud/domain/weather/util/WeatherApiParser.java
  src/main/java/com/techeer/fashioncloud/domain/weather/util/WindChillCalculator.java
  src/main/java/com/techeer/fashioncloud/global/config/GeoConfig.java
  src/main/java/com/techeer/fashioncloud/global/config/WeatherConfig.java
  src/main/java/com/techeer/fashioncloud/global/error/ErrorCode.java
  src/main/java/com/techeer/fashioncloud/global/error/GlobalExceptionHandler.java
  src/main/java/com/techeer/fashioncloud/global/error/exception/ExternalApiException.java
  src/main/java/com/techeer/fashioncloud/global/util/api/ExternalApiCallable.java
  src/main/java/com/techeer/fashioncloud/global/util/api/dto/ExternalApiRequest.java
  src/main/resources/application.yml
Labels: 리팩토링

#106 [feat/#102] swagger설정
  src/main/java/com/techeer/fashioncloud/domain/geo/controller/AddressController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/LookBookController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/S3Controller.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/WeatherController.java
Labels: 기능구현
