Repository Fashion-Cloud/backend, pull requests merged in 2023-06, with the labels that each got.

#80 [Feat/#76] lookbook 관련 crud 제작
  src/main/java/com/techeer/fashioncloud/domain/post/controller/LookBookController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/mapper/LookBookMapper.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/BookCreateRequestDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/LookBookCreateRequestDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/response/BookResponseDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/response/LookBookDataDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/response/LookBookResponseDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Book.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/LookBook.java
  src/main/java/com/techeer/fashioncloud/domain/post/exception/BookNotFoundException.java
  src/main/java/com/techeer/fashioncloud/domain/post/exception/LookBookNotFoundException.java
  src/main/java/com/techeer/fashioncloud/domain/post/repository/BookRepository.java
  src/main/java/com/techeer/fashioncloud/domain/post/repository/LookBookRepository.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/LookBookService.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
  src/main/java/com/techeer/fashioncloud/global/error/ErrorCode.java
  src/main/java/com/techeer/fashioncloud/global/response/ResponseCode.java
Labels: 기능구현, 리팩토링

#79 [feat/#78] pagenation 적용
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/mapper/PostMapper.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
Labels: 기능구현

#83 [Refactor/#82] weather enum에서 integer 상수로 변경
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostCreateServiceDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Post.java
  src/main/java/com/techeer/fashioncloud/domain/post/repository/PostRepository.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/constant/RainfallType.java
  src/main/java/com/techeer/fashioncloud/domain/weather/constant/SkyStatus.java
Labels: 리팩토링

#90 [fix/#86] coors에러 임시 해결
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/S3Controller.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/AddressController.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/WeatherController.java
Labels: 이슈해결
