Repository Fashion-Cloud/backend, pull requests merged in 2023-10, with the labels that each got.

#123 [Feat/#117] location entity 구현
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Location.java
Labels: 기능구현

#119 [feat/#118] 회원가입, 로그인
  build.gradle
  src/main/java/com/techeer/fashioncloud/domain/auth/ROLE.java
  src/main/java/com/techeer/fashioncloud/domain/auth/controller/AuthController.java
  src/main/java/com/techeer/fashioncloud/domain/auth/dto/request/LoginRequestDto.java
  src/main/java/com/techeer/fashioncloud/domain/auth/dto/request/SignupRequestDto.java
  src/main/java/com/techeer/fashioncloud/domain/auth/dto/response/SignupResponseDto.java
  src/main/java/com/techeer/fashioncloud/domain/auth/dto/response/Token.java
  src/main/java/com/techeer/fashioncloud/domain/auth/service/AuthService.java
  src/main/java/com/techeer/fashioncloud/domain/auth/service/CustomUserDetailService.java
  src/main/java/com/techeer/fashioncloud/domain/auth/util/TokenProvider.java
  src/main/java/com/techeer/fashioncloud/domain/geo/controller/AddressController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/LookBookController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/user/entity/User.java
  src/main/java/com/techeer/fashioncloud/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/WeatherController.java
  src/main/java/com/techeer/fashioncloud/global/config/CorsConfig.java
  src/main/java/com/techeer/fashioncloud/global/config/RedisConfig.java
  src/main/java/com/techeer/fashioncloud/global/config/SecurityConfig.java
  src/main/java/com/techeer/fashioncloud/global/config/WebConfig.java
  src/main/java/com/techeer/fashioncloud/global/error/ErrorCode.java
  src/main/java/com/techeer/fashioncloud/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/techeer/fashioncloud/global/error/handler/JwtAccessDeniedHandler.java
  src/main/java/com/techeer/fashioncloud/global/error/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/techeer/fashioncloud/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/techeer/fashioncloud/global/response/ResponseCode.java
  src/main/resources/application.yml
Labels: 기능구현

#125 [feat/#124] 팔로우/팔로잉 기능 구현
  src/main/java/com/techeer/fashioncloud/domain/post/controller/LookBookController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/S3Controller.java
  src/main/java/com/techeer/fashioncloud/domain/user/controller/UserController.java
  src/main/java/com/techeer/fashioncloud/domain/user/dto/response/FollowInfoResponseDto.java
  src/main/java/com/techeer/fashioncloud/domain/user/dto/response/FollowListResponseDto.java
  src/main/java/com/techeer/fashioncloud/domain/user/entity/Follow.java
  src/main/java/com/techeer/fashioncloud/domain/user/entity/User.java
  src/main/java/com/techeer/fashioncloud/domain/user/repository/FollowRepository.java
  src/main/java/com/techeer/fashioncloud/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/fashioncloud/domain/user/service/UserService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/global/config/SecurityConfig.java
  src/main/java/com/techeer/fashioncloud/global/error/ErrorCode.java
  src/main/java/com/techeer/fashioncloud/global/response/ResponseCode.java
Labels: 기능구현

#122 [Feat/#121] region테이블 생성
  src/main/java/com/techeer/fashioncloud/domain/geo/entity/Region.java
Labels: 기능구현

#136 [docs/#134] swagger에 인증 버튼 추가
  src/main/java/com/techeer/fashioncloud/global/config/SwaggerConfig.java
Labels: 문서

#138 refactor: @LoginUser사용하도록 변경
  src/main/java/com/techeer/fashioncloud/domain/user/controller/UserController.java
  src/main/java/com/techeer/fashioncloud/domain/user/service/UserService.java
Labels: 리팩토링

#140 feat: 타임라인 조회 복구
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/repository/PostRepository.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
Labels: 기능구현

#141 [feat/#132] 로그인한 사용자 정보 조회 api
  src/main/java/com/techeer/fashioncloud/domain/user/controller/UserController.java
  src/main/java/com/techeer/fashioncloud/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/techeer/fashioncloud/domain/user/entity/User.java
  src/main/java/com/techeer/fashioncloud/domain/user/service/UserService.java
  src/main/java/com/techeer/fashioncloud/global/response/ResponseCode.java
Labels: 기능구현
