Repository Fashion-Cloud/backend, pull requests merged in 2023-05, with the labels that each got.

#43 [Refactor/#42] apiResponse수정
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/controller/S3Controller.java
  src/main/java/com/techeer/fashioncloud/global/response/ResponseCode.java
Labels: 리팩토링

#41 refactor:입력범위 예외처리
  src/main/java/com/techeer/fashioncloud/domain/weather/position/Location.java
Labels: 리팩토링

#50 refactor: 파싱 중복 로직 분리, 기상청 resultCode에따른 예외처리
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/AddressController.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/WeatherController.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/ForecastResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/UltraSrtNcstResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/WeatherInfoResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/Forecast.java
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/UltraSrtFcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/UltraSrtNcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/VilageFcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/exception/KakaoApiException.java
  src/main/java/com/techeer/fashioncloud/domain/weather/exception/WeatherApiException.java
  src/main/java/com/techeer/fashioncloud/domain/weather/position/Location.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/AddressService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/global/error/GlobalExceptionHandler.java
  src/main/java/com/techeer/fashioncloud/global/error/exception/ExternalApiException.java
Labels: 리팩토링

#49 [Feat/#39] Post create update find 서비스 테스트코드 작성
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostCreateServiceDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Post.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
  src/test/java/com/techeer/fashioncloud/domain/post/service/PostServiceTest.java
  src/test/java/com/techeer/fashioncloud/fixture/PostFixtures.java
Labels: 기능구현

#54 [Refactor/#53] openApi 호출 request requestbody -> parameter로 변경
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/response/WeatherPostResponse.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Post.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/AddressController.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/WeatherController.java
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/Forecast.java
  src/main/java/com/techeer/fashioncloud/domain/weather/exception/KakaoApiException.java
  src/main/java/com/techeer/fashioncloud/domain/weather/exception/WeatherApiException.java
  src/main/java/com/techeer/fashioncloud/global/dto/LocationDto.java
  src/main/java/com/techeer/fashioncloud/global/error/ExternalErrorResponse.java
  src/main/java/com/techeer/fashioncloud/global/error/GlobalExceptionHandler.java
  src/main/java/com/techeer/fashioncloud/global/error/exception/ExternalApiException.java
Labels: 리팩토링

#55 [Refactor/#51] 기상청 openApi호출 중복 로직 메소드 분리
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostWeatherRequest.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Post.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/global/error/GlobalExceptionHandler.java
Labels: 리팩토링

#61 refactor: 날씨 전달 방식 변경 및 풍속 오류 수정
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostWeatherRequest.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/constant/SkyStatus.java
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/UltraSrtNcst.java
Labels: 리팩토링

#58 [refactor/#57] 체감온도에 풍속값 -> 체감온도로 수정
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
  src/main/java/com/techeer/fashioncloud/global/util/WindChillCalculator.java
Labels: 기능구현, 리팩토링

#62 [refactor/#52] 맑음데이터 게시글 조회 수정, 더미데이터 삽입
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: 리팩토링

#67 Feat/#65 redis 캐싱
  build.gradle
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/global/config/RedisCacheConfig.java
  src/main/java/com/techeer/fashioncloud/global/config/RedisConfig.java
  src/main/java/com/techeer/fashioncloud/global/error/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: 기능구현

#68 [chore/#192] gitignore에 .idea추가
  .gitignore
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
Labels: 환경설정

#70 refactor: 카카오 api 호출부분 추상화
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/UltraSrtFcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/AddressService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/global/domain/ExternalApiCallable.java
  src/main/resources/application.yml
Labels: 리팩토링

#74 [fix/#71] redis연결설정 테스트를 위한 컨트롤러 작성 및 Dockerfile 수정
  Dockerfile
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/global/config/RedisConfig.java
  src/main/java/com/techeer/fashioncloud/redis/RedisController.java
  src/main/java/com/techeer/fashioncloud/redis/RedisService.java
  src/main/resources/application.yml
Labels: 이슈해결

#77 [Feat/#75] 캐시 업데이트
  src/main/java/com/techeer/fashioncloud/FashioncloudApplication.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Post.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/WeatherController.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherCacheService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/global/config/RedisCacheConfig.java
  src/main/java/com/techeer/fashioncloud/global/config/RedisConfig.java
  src/main/java/com/techeer/fashioncloud/redis/RedisController.java
  src/main/java/com/techeer/fashioncloud/redis/RedisService.java
  src/main/resources/application.yml
Labels: 기능구현
