Repository Fashion-Cloud/backend, pull requests merged in 2023-04, with the labels that each got.

#17 [Feat/#16] 위도,경도 ->x,y좌표값으로 변경
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/UltraSrtFcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/entity/UltraSrtNcst.java
  src/main/java/com/techeer/fashioncloud/domain/weather/position/Coordinate.java
  src/main/java/com/techeer/fashioncloud/domain/weather/position/Location.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
Labels: 기능구현

#18 [Feat/#15] 카카오 api 호출하여 위경도 -> 주소 변환
  src/main/java/com/techeer/fashioncloud/domain/weather/constant/GeoConstant.java
  src/main/java/com/techeer/fashioncloud/domain/weather/controller/AddressController.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/AddressResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/position/Location.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/AddressService.java
  src/main/java/com/techeer/fashioncloud/global/config/GeoConfig.java
Labels: 기능구현

#14 [feat/#11] post CRUD 제작
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/mapper/PostMapper.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostCreateServiceDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Post.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/PostCategory.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Review.java
  src/main/java/com/techeer/fashioncloud/domain/post/repository/PostRepository.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
Labels: 기능구현

#25 [Refactor/#24] Post CRUD 코드 수정
  build.gradle
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/mapper/PostMapper.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/repository/PostRepository.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
Labels: 리팩토링

#23 [Feat/#22] 날씨 필터링하여 post 조회
  build.gradle
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/mapper/PostMapper.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostWeatherRequest.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/response/WeatherPostResponse.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Post.java
  src/main/java/com/techeer/fashioncloud/domain/post/repository/PostRepository.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
  src/main/java/com/techeer/fashioncloud/domain/weather/constant/ForecastConstant.java
  src/main/java/com/techeer/fashioncloud/domain/weather/constant/RainfallType.java
  src/main/java/com/techeer/fashioncloud/domain/weather/constant/SkyStatus.java
  src/main/java/com/techeer/fashioncloud/domain/weather/dto/WeatherInfoResponse.java
  src/main/java/com/techeer/fashioncloud/domain/weather/service/WeatherService.java
  src/main/java/com/techeer/fashioncloud/global/util/WindChillCalculator.java
Labels: 기능구현

#29 [refactor/#28] post entity 변경사항 수정
  src/main/java/com/techeer/fashioncloud/domain/post/dto/mapper/PostMapper.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/dto/request/PostCreateServiceDto.java
  src/main/java/com/techeer/fashioncloud/domain/post/entity/Post.java
  src/main/java/com/techeer/fashioncloud/domain/post/service/PostService.java
Labels: 리팩토링

#31 [chore/#30] 백엔드 도커 파일 구축
  Dockerfile
Labels: 기능구현, 환경설정

#34 [fix/#33]upate api
  src/main/java/com/techeer/fashioncloud/domain/post/controller/PostController.java
Labels: 리팩토링
